'0':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'1':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'2':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'3':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'4':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'5':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'6':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'8':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]
'9':
  transform_mtx: 
  - [0, 0, -1, 0.0]
  - [0, -1, 0, 0.1]
  - [-1, 0, 0, 0.0]
  - [0.0, 0, 0, 1.0]